---
- name: Configure rsyslog on client servers
  hosts: client_servers
  become: yes
  tasks:
    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present

    - name: Copy rsyslog client configuration
      template:
        src: rsyslog_client.conf.j2
        dest: /etc/rsyslog.d/50-default.conf
      notify:
        - restart rsyslog on clients

    - name: Ensure rsyslog is running and enabled on boot
      service:
        name: rsyslog
        state: started
        enabled: yes

  handlers:
    - name: restart rsyslog on clients
      service:
        name: rsyslog
        state: restarted
