---
- name: Install Zabbix Server
  hosts: localhost
  connection: local 
  become: yes
  vars:
    zabbix_version: "5.0"
    zabbix_db_name: "larsDB"
    zabbix_db_user: "lars"
    zabbix_db_password: "test"

  tasks:
    - name: Install necessary packages
      apt:
        name:
          - mysql-server
          - mysql-client
          - php
          - php-mysql
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Secure MySQL installation
      mysql_secure_installation:
        login_password: ''
        login_user: root
        new_password: 'test'
        user: root
        change_root_password: yes

    - name: Create Zabbix database
      mysql_db:
        name: "{{ zabbix_db_name }}"
        state: present
        login_user: root
        login_password: "test"

    - name: Create Zabbix user
      mysql_user:
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_password }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "test"

    - name: Install Zabbix repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu $(lsb_release -cs) main"
        state: present
        update_cache: yes

    - name: Install Zabbix server and frontend
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
        state: present

    - name: Start Zabbix server
      service:
        name: zabbix-server
        state: started
        enabled: yes
